import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/ui/themeProvider";
import { Toaster } from "@/components/ui/toaster";
import Nav from "@/components/ui/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <>
            <main className="w-screen flex justify-center bg-neutral-950">
              <Nav />
              <div className="min-h-screen text-base w-full max-w-[500px] bg-neutral-950 relative pb-14">
                {children}
              </div>
            </main>
            <Toaster />
          </>
        </ThemeProvider>
      </body>
    </html>
  );
}
